version: '3.9' # Using version 3.9
services:
  db:
    image: arm64v8/mongo # Using the mongodb community edition image
    ports: 
      - 27017:27017 # Exposing port 27017 so that mongodb can be accessed outside
    restart: unless-stopped # Setting the restart policy so that the container always restarts unless stopped
    volumes:
      - mongodb_data:/data/db # Creating the volume 'mongodb_data' to protect the data in '/data/db'
    networks: 
      - dbnet # Connecting the container to the dbnet network
volumes:
  mongodb_data:
networks:
  dbnet:
