version: '3.9' # Using version 3.9
services:
  db:
    image: mongo:bionic # Using the mongodb bionic image (so it can be compatible with the raspberry pi's ARM architecture)
    ports: 
      - 27017:27017 # Exposing port 27017 so that mongodb can be accessed outside
    restart: unless-stopped # Setting the restart policy so that the container always restarts unless stopped
    volumes:
      - mongodb_data:/data/db # Creating the volume 'mongodb_data' to protect the data in '/data/db'
    networks: 
      - dbnet # Connecting the container to the dbnet network
volumes:
  mongodb_data:
networks:
  dbnet:
